// notes-frontend/src/app/components/create-document/create-document.component.ts
import { Component, OnInit } from '@angular/core';
import { EditorComponent } from '@tinymce/tinymce-angular';

@Component({
  selector: 'app-create-document',
  templateUrl: './create-document.component.html',
  styleUrls: ['./create-document.component.scss']
})
export class CreateDocumentComponent implements OnInit {

  documentContent: any;

  constructor() { }

  ngOnInit(): void {
  }

  handleInput(content: any) {
    console.log("Hej" + content)
  }

  saveDoc(title: string, content: any) {
    console.log("titel: " + title)
    console.log("content: " + content)
    console.log("Klickat på Spara dokument")
    // console.log(this.documentContent)
  }

}

<section>
    <input type="text" placeholder="Titel" #title>
    <editor 
        apiKey="sy5qpdvs7ygvd1tcyaxond8i4ywqzo5s8aw3ui3jev7zr7lh"
        (onSaveContent)="handleInput(content)"
        [init]="{
            menubar: false,
            toolbar: 
            'undo redo | bold italic underline | backcolor forecolor | \
            alignleft aligncenter alignright | outdent indent'
        }"
        #content >
    </editor>

    <button (click)="saveDoc(title.value, content)">Spara dokument</button>
</section>

// frontend-react/src/components/CreateDocument.tsx
// import React, { useRef } from 'react';
import { Editor } from '@tinymce/tinymce-react';

export function CreateDocument() {

    // const editorRef = useRef(null);

    // const log = () => {
    //     if (editorRef.current) {
    //       console.log(editorRef.current.getContent());
    //     }
    // };


    function createNewDoc() {
        console.log("Klickat i editorn", Editor)
    }


    // function getContent() {
    //     console.log("getContent")
    // }

    return (
      <>
        <input type="text" placeholder='Titel'/>
        <Editor
            apiKey='sy5qpdvs7ygvd1tcyaxond8i4ywqzo5s8aw3ui3jev7zr7lh'
            //   onInit={(evt, editor) => editorRef.current = editor}
            init={{
                // selector: "#textArea",
                height: 500,
                menubar: false,
                plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
                ],
                toolbar: ' undo redo | bold italic backcolor | ' +
                ' alignleft alignright | outdent indent | '
            }}
        />
        <button onClick={createNewDoc}>Skapa dokument</button>

        {/* <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"></script> */}
      </>
    );
};
